In [42]:
import pandas as pd
import numpy as np
import os
import plotly.express as px
import plotly.graph_objects as go

os.chdir("/Users/michael/Desktop/Website Data/")
print("Current working directory:", os.getcwd())

Current working directory: /Users/michael/Desktop/Website Data

# Cleaning

In [51]:
onlineExcel = pd.ExcelFile("Datasets/acsw-survey-albertans-data-file-2022-2023.xlsx")
onlineRaw = pd.read_excel(onlineExcel, "2022-23 Survey of Albertans Dat")
onlineQuestions = pd.read_excel(onlineExcel, "Questions")

In [52]:
onlineQuestions

        Variable                                              Label
0      sample_id                                             <none>
1     weight_rga       weight_rga -- Weight (Region / Gender / Age)
2             q1             q1 -- What age range do you fall into?
3             q2              q2 -- Region (based on FSA/community)
4             q3  q3 -- How do you describe your gender identity...
...          ...                                                ...
1194       d9_13  d9_13 -- Multiple racial identities : How woul...
1195       d9_14  d9_14 -- Prefer to self-describe : How would y...
1196      d9_14_  d9_14_ -- Prefer to self-describe : How would ...
1197         d10            d10 -- What is your sexual orientation?
1198      d10_8_  d10_8_ -- Prefer to self-describe : What is yo...

[1199 rows x 2 columns]

In [45]:
rename_dict = dict(zip(
    onlineQuestions['Variable'],  # Original names
    onlineQuestions['Label'].str.split('--').str[1].str.strip()  # Clean labels
))

rename_dict.update({"sample_id": "sample_id"}) 

renamedOnline22 = onlineRaw.rename(columns = rename_dict)

                    #Demographic Questions
demographicQuestions = [
                    "What age range do you fall into?",
                    "What is the highest level of education you have completed?",
                    "What is your employment status?",
                    "Do you have any children, living at home or that you are a legal guardian for, who are under 18 years old?"]

    
                    #Volunteering Amount and Categories
volunteeringBehaviour = [
                    "Formal volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?",
                    "Informal volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?",
                    "No volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?",
                    "Any Volunteering  : Which, if any, type(s) of volunteering have you done in the past 12 months?",
                    "Was the formal volunteering that you did in the past 12 months your first time formally volunteering in Alberta? [Do formal volunteering]",
                    "In the past 12 months, on average, about how many hours per month did you spend formally volunteering? [Do formal volunteering]",
                    "[Bucketed] In the past 12 months, on average, about how many hours per month did you spend formally volunteering? [Do formal volunteering]",
                    "Social Services : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
                    "Faith-based Groups : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
                    "Fundraising/Philanthropic Organizations : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
                    "Sports & Recreation : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
                    "Education & Research : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
                    "Youth Development : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
                    "Community Development : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
                    "Environment : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
                    "Unions & Professional Associations : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
                    "Arts & Culture : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
                    "Hospitals or Health : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
                    "Law, Advocacy, & Politics : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
                    "Other volunteer area : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
                    "Other volunteer area : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
                    "Micro Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]",
                    "Virtual/ Online Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]",
                    "Group Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]",
                    "Employer Supported Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]",
                    "None of the above : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]",
                    "Friends, family members, or neighbours : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
                    "Colleagues : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
                    "Social Media : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
                    "Employers : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
                    "Volunteer Centers : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
                    "Church / Religious group : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
                    "Alberta Cares Connector, or the Volunteer Connector : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
                    "Online / General web search  : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
                    "Past experience : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
                    "School / College / University : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
                    "Sports teams / Sports organizations : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
                    "Other : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
                    "Other : How did you find out about the formal volunteering opportunities you participated in?",
                    "In the past 12 months, on average, about how many hours per month did you spend informally volunteering? [Do informal volunteering]",
                    "[Bucketed] In the past 12 months, on average, about how many hours per month did you spend informally volunteering? [Do informal volunteering]",
                    "Was the informal volunteering you did in the past 12 months your first time informally volunteering in Alberta? [Do informal volunteering]"]

                    #Challenges questions
challengesQuestions = ["Opportunities did not match or improve my skill set : Which, if any, challenges have you ever been faced with when volunteering?",
                    "Lack of available time : Which, if any, challenges have you ever been faced with when volunteering?",
                    "Language Skills : Which, if any, challenges have you ever been faced with when volunteering?",
                    "Personal Health : Which, if any, challenges have you ever been faced with when volunteering?",
                    "Age : Which, if any, challenges have you ever been faced with when volunteering?",
                    "Cost/Financial : Which, if any, challenges have you ever been faced with when volunteering?",
                    "Location of volunteering : Which, if any, challenges have you ever been faced with when volunteering?",
                    "Finding Volunteer opportunities : Which, if any, challenges have you ever been faced with when volunteering?",
                    "No one asked : Which, if any, challenges have you ever been faced with when volunteering?",
                    "Unhappy with previous volunteer experience(s) : Which, if any, challenges have you ever been faced with when volunteering?",
                    "Lack of flexible scheduling : Which, if any, challenges have you ever been faced with when volunteering?",
                    "Lack of support for volunteering at different locations : Which, if any, challenges have you ever been faced with when volunteering?",
                    "Did not accommodate groups or families : Which, if any, challenges have you ever been faced with when volunteering?",
                    "Did not offer accommodations to those with health issues : Which, if any, challenges have you ever been faced with when volunteering?",
                    "Did not appear to be welcoming and inclusive to all Albertans : Which, if any, challenges have you ever been faced with when volunteering?",
                    "Unclear or unreasonable expectations : Which, if any, challenges have you ever been faced with when volunteering?",
                    "Volunteer recruitment or interview processes : Which, if any, challenges have you ever been faced with when volunteering?",
                    "Required too much or too little of my time : Which, if any, challenges have you ever been faced with when volunteering?",
                    "Other challenges : Which, if any, challenges have you ever been faced with when volunteering?",
                    "None of the above : Which, if any, challenges have you ever been faced with when volunteering?",
                    "I have never volunteered : Which, if any, challenges have you ever been faced with when volunteering?",
                    "Other challenges : Which, if any, challenges have you ever been faced with when volunteering?"]
                        
                    #To What Extent Questions 
toWhatExtentQuestions = [
                    "Access to volunteer opportunities that match and help improve my skill set. : To what extent would each of the following make formal volunteering more appealing for you?",
                    "Access to volunteer opportunities that offer flexible schedules. : To what extent would each of the following make formal volunteering more appealing for you?",
                    "Access to volunteer opportunities that offer training with current technology : To what extent would each of the following make formal volunteering more appealing for you?",
                    "Organizations that support different ways of volunteering : To what extent would each of the following make formal volunteering more appealing for you?",
                    "Organizations that support group or family volunteering opportunities. : To what extent would each of the following make formal volunteering more appealing for you?",
                    "Organizations that are welcoming and inclusive to all Albertans. : To what extent would each of the following make formal volunteering more appealing for you?",
                    "Organizations that understand and work to meet the needs of my community. : To what extent would each of the following make formal volunteering more appealing for you?",
                    "Organizations that regularly recognize the contributions of volunteers. : To what extent would each of the following make formal volunteering more appealing for you?",
                    "Volunteers are important contributors to Alberta's economy. : To what extent do you agree with the following statements?",
                    "Volunteering is for people of all ages. : To what extent do you agree with the following statements?",
                    "Whether large or small, all contributions by volunteers make a positive difference in the community. : To what extent do you agree with the following statements?",
                    "Provides an opportunity to give back to the community/make the community a better place to live. : To what extent do you agree that each of the following are benefits of volunteering?",
                    "Provides an opportunity to make meaningful connections with people. : To what extent do you agree that each of the following are benefits of volunteering?",
                    "Supports your own physical and/or mental health and wellness. : To what extent do you agree that each of the following are benefits of volunteering?"]

onlineQuestionsWanted = (demographicQuestions+volunteeringBehaviour+challengesQuestions+toWhatExtentQuestions)

cleanData = renamedOnline22[onlineQuestionsWanted].copy()

for col in cleanData.columns:
    cleanData[col] = cleanData[col].apply(lambda x: str(x)[4:])

                                                                      
# naValueDict = {
#     "(-7) Skipped": pd.NA,
#     "(-9) Don't know": pd.NA,
#     "(-8) Prefer not to say": pd.NA,
#     "(-8) Prefer not to answer": pd.NA,
#     "(-8) Refused":pd.NA,
# #    "(0) Not selected":pd.NA
# }

#cleanData = cleanData.replace(naValueDict)

/var/folders/sd/wv_nm0y1393428nsbk57c67w0000gn/T/ipykernel_4601/1163233276.py:109: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  cleanData[col] = cleanData[col].apply(lambda x: str(x)[4:])

In [50]:
renamedOnline22.head()

,sample_id,Weight (Region / Gender / Age),What age range do you fall into?,Region (based on FSA/community),How do you describe your gender identity or expression?,Prefer to self-describe : How do you describe your gender identity or expression?,"Do you have any children, living at home or that you are a legal guardian for, who are under 18 years old?","In the past 12 months, have you participated in any organized sport activities?",Archery : [Top 1] Which organized sport activities have you participated in during the past 12 months? [Participated in organized sport],Cricket : [Top 1] Which organized sport activities have you participated in during the past 12 months? [Participated in organized sport],...,Latin American : How would you describe your racial identity?,Arab : How would you describe your racial identity?,Japanese : How would you describe your racial identity?,West Asian : How would you describe your racial identity?,Korean : How would you describe your racial identity?,Multiple racial identities : How would you describe your racial identity?,Prefer to self-describe : How would you describe your racial identity?,Prefer to self-describe : How would you describe your racial identity?,What is your sexual orientation?,Prefer to self-describe : What is your sexual orientation?
0,4668,1.610713,(2) 18 to 24,(1) Calgary,(2) Man,NaN,(0) No,(1) Yes,(0) Not selected,(0) Not selected,...,(-8) Refused,(-8) Refused,(-8) Refused,(-8) Refused,(-8) Refused,(-8) Refused,(-8) Refused,NaN,(-8) Prefer not to answer,NaN
1,3829,1.610713,(3) 25 to 34,(1) Calgary,(2) Man,NaN,(0) No,(0) No,(-7) Skipped,(-7) Skipped,...,(0) Not selected,(0) Not selected,(0) Not selected,(0) Not selected,(0) Not selected,(0) Not selected,(0) Not selected,NaN,(1) Straight/heterosexual,NaN
2,4119,1.610713,(2) 18 to 24,(1) Calgary,(2) Man,NaN,(0) No,(0) No,(-7) Skipped,(-7) Skipped,...,(1) Selected,(0) Not selected,(0) Not selected,(0) Not selected,(0) Not selected,(0) Not selected,(0) Not selected,NaN,(4) Bisexual,NaN
3,2091,1.610713,(2) 18 to 24,(1) Calgary,(2) Man,NaN,(0) No,(0) No,(-7) Skipped,(-7) Skipped,...,(0) Not selected,(0) Not selected,(0) Not selected,(0) Not selected,(0) Not selected,(0) Not selected,(0) Not selected,NaN,(-8) Prefer not to answer,NaN
4,3855,1.610713,(2) 18 to 24,(1) Calgary,(2) Man,NaN,(0) No,(0) No,(-7) Skipped,(-7) Skipped,...,(0) Not selected,(0) Not selected,(0) Not selected,(0) Not selected,(0) Not selected,(0) Not selected,(0) Not selected,NaN,(1) Straight/heterosexual,NaN

In [46]:
cleanData.head()

,What age range do you fall into?,What is the highest level of education you have completed?,What is your employment status?,"Do you have any children, living at home or that you are a legal guardian for, who are under 18 years old?","Formal volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?","Informal volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?","No volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?","Any Volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?",Was the formal volunteering that you did in the past 12 months your first time formally volunteering in Alberta? [Do formal volunteering],"In the past 12 months, on average, about how many hours per month did you spend formally volunteering? [Do formal volunteering]",...,Organizations that support group or family volunteering opportunities. : To what extent would each of the following make formal volunteering more appealing for you?,Organizations that are welcoming and inclusive to all Albertans. : To what extent would each of the following make formal volunteering more appealing for you?,Organizations that understand and work to meet the needs of my community. : To what extent would each of the following make formal volunteering more appealing for you?,Organizations that regularly recognize the contributions of volunteers. : To what extent would each of the following make formal volunteering more appealing for you?,Volunteers are important contributors to Alberta's economy. : To what extent do you agree with the following statements?,Volunteering is for people of all ages. : To what extent do you agree with the following statements?,"Whether large or small, all contributions by volunteers make a positive difference in the community. : To what extent do you agree with the following statements?",Provides an opportunity to give back to the community/make the community a better place to live. : To what extent do you agree that each of the following are benefits of volunteering?,Provides an opportunity to make meaningful connections with people. : To what extent do you agree that each of the following are benefits of volunteering?,Supports your own physical and/or mental health and wellness. : To what extent do you agree that each of the following are benefits of volunteering?
0,18 to 24,Graduated university,Student,No,Not selected,Not selected,Selected,Not selected,Skipped,Skipped,...,Moderately more appealing,Not at all,A lot more appealing,A little bit more appealing,Agree a little bit,Strongly agree,Moderately agree,Strongly agree,Moderately agree,Strongly agree
1,25 to 34,Graduated university,Working full-time,No,Not selected,Not selected,Selected,Not selected,Skipped,Skipped,...,Moderately more appealing,A little bit more appealing,Moderately more appealing,Moderately more appealing,Agree a little bit,Moderately agree,Strongly agree,Moderately agree,Agree a little bit,Moderately agree
2,18 to 24,"Graduated college, apprenticeship or trades",Working full-time,No,Refused,Refused,Refused,Refused,Skipped,Skipped,...,Don't know,Don't know,Don't know,Don't know,Don't know,Don't know,Don't know,Don't know,Don't know,Don't know
3,18 to 24,Not graduated from high school,Unemployed,No,Not selected,Selected,Not selected,Selected,Skipped,Skipped,...,Moderately more appealing,A lot more appealing,Moderately more appealing,A lot more appealing,Strongly agree,Strongly agree,Strongly agree,Moderately agree,Strongly agree,Moderately agree
4,18 to 24,Some university,Working part-time,No,Selected,Not selected,Not selected,Selected,No,Don't know,...,A lot more appealing,A lot more appealing,A lot more appealing,A lot more appealing,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Moderately agree

In [47]:
list(cleanData)

['What age range do you fall into?',
 'What is the highest level of education you have completed?',
 'What is your employment status?',
 'Do you have any children, living at home or that you are a legal guardian for, who are under 18 years old?',
 'Formal volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?',
 'Informal volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?',
 'No volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?',
 'Any Volunteering  : Which, if any, type(s) of volunteering have you done in the past 12 months?',
 'Was the formal volunteering that you did in the past 12 months your first time formally volunteering in Alberta? [Do formal volunteering]',
 'In the past 12 months, on average, about how many hours per month did you spend formally volunteering? [Do formal volunteering]',
 '[Bucketed] In the past 12 months, on average, about how many hours per month did you spend formally volunteering? [Do formal volunteering]',
 'Social Services : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Faith-based Groups : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Fundraising/Philanthropic Organizations : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Sports & Recreation : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Education & Research : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Youth Development : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Community Development : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Environment : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Unions & Professional Associations : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Arts & Culture : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Hospitals or Health : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Law, Advocacy, & Politics : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Other volunteer area : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Other volunteer area : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Other volunteer area : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Other volunteer area : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Micro Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]',
 'Virtual/ Online Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]',
 'Group Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]',
 'Employer Supported Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]',
 'None of the above : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]',
 'Friends, family members, or neighbours : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Colleagues : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Social Media : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Employers : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Volunteer Centers : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Church / Religious group : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Alberta Cares Connector, or the Volunteer Connector : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Online / General web search  : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Past experience : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'School / College / University : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Sports teams / Sports organizations : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Other : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Other : How did you find out about the formal volunteering opportunities you participated in?',
 'In the past 12 months, on average, about how many hours per month did you spend informally volunteering? [Do informal volunteering]',
 '[Bucketed] In the past 12 months, on average, about how many hours per month did you spend informally volunteering? [Do informal volunteering]',
 'Was the informal volunteering you did in the past 12 months your first time informally volunteering in Alberta? [Do informal volunteering]',
 'Opportunities did not match or improve my skill set : Which, if any, challenges have you ever been faced with when volunteering?',
 'Lack of available time : Which, if any, challenges have you ever been faced with when volunteering?',
 'Language Skills : Which, if any, challenges have you ever been faced with when volunteering?',
 'Personal Health : Which, if any, challenges have you ever been faced with when volunteering?',
 'Age : Which, if any, challenges have you ever been faced with when volunteering?',
 'Cost/Financial : Which, if any, challenges have you ever been faced with when volunteering?',
 'Location of volunteering : Which, if any, challenges have you ever been faced with when volunteering?',
 'Finding Volunteer opportunities : Which, if any, challenges have you ever been faced with when volunteering?',
 'No one asked : Which, if any, challenges have you ever been faced with when volunteering?',
 'Unhappy with previous volunteer experience(s) : Which, if any, challenges have you ever been faced with when volunteering?',
 'Lack of flexible scheduling : Which, if any, challenges have you ever been faced with when volunteering?',
 'Lack of support for volunteering at different locations : Which, if any, challenges have you ever been faced with when volunteering?',
 'Did not accommodate groups or families : Which, if any, challenges have you ever been faced with when volunteering?',
 'Did not offer accommodations to those with health issues : Which, if any, challenges have you ever been faced with when volunteering?',
 'Did not appear to be welcoming and inclusive to all Albertans : Which, if any, challenges have you ever been faced with when volunteering?',
 'Unclear or unreasonable expectations : Which, if any, challenges have you ever been faced with when volunteering?',
 'Volunteer recruitment or interview processes : Which, if any, challenges have you ever been faced with when volunteering?',
 'Required too much or too little of my time : Which, if any, challenges have you ever been faced with when volunteering?',
 'Other challenges : Which, if any, challenges have you ever been faced with when volunteering?',
 'Other challenges : Which, if any, challenges have you ever been faced with when volunteering?',
 'None of the above : Which, if any, challenges have you ever been faced with when volunteering?',
 'I have never volunteered : Which, if any, challenges have you ever been faced with when volunteering?',
 'Other challenges : Which, if any, challenges have you ever been faced with when volunteering?',
 'Other challenges : Which, if any, challenges have you ever been faced with when volunteering?',
 'Access to volunteer opportunities that match and help improve my skill set. : To what extent would each of the following make formal volunteering more appealing for you?',
 'Access to volunteer opportunities that offer flexible schedules. : To what extent would each of the following make formal volunteering more appealing for you?',
 'Access to volunteer opportunities that offer training with current technology : To what extent would each of the following make formal volunteering more appealing for you?',
 'Organizations that support different ways of volunteering : To what extent would each of the following make formal volunteering more appealing for you?',
 'Organizations that support group or family volunteering opportunities. : To what extent would each of the following make formal volunteering more appealing for you?',
 'Organizations that are welcoming and inclusive to all Albertans. : To what extent would each of the following make formal volunteering more appealing for you?',
 'Organizations that understand and work to meet the needs of my community. : To what extent would each of the following make formal volunteering more appealing for you?',
 'Organizations that regularly recognize the contributions of volunteers. : To what extent would each of the following make formal volunteering more appealing for you?',
 "Volunteers are important contributors to Alberta's economy. : To what extent do you agree with the following statements?",
 'Volunteering is for people of all ages. : To what extent do you agree with the following statements?',
 'Whether large or small, all contributions by volunteers make a positive difference in the community. : To what extent do you agree with the following statements?',
 'Provides an opportunity to give back to the community/make the community a better place to live. : To what extent do you agree that each of the following are benefits of volunteering?',
 'Provides an opportunity to make meaningful connections with people. : To what extent do you agree that each of the following are benefits of volunteering?',
 'Supports your own physical and/or mental health and wellness. : To what extent do you agree that each of the following are benefits of volunteering?']

In [49]:
#reorganizedData["Which, if any, type(s) of volunteering have you done in the past 12 months?"]

reorganizedData = pd.DataFrame()
reorganizedData[demographicQuestions] = cleanData[demographicQuestions]

for col in volunteeringBehaviour:
    if ":" in col:
        answer, question = col.split(":")
        print(question)
        reorganizedData[question] = cleanData[cleanData[col] == "Selected"][col]

reorganizedData.head()



#                     "Formal volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?",
#                     "Informal volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?",
#                     "No volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?",
#                     "Any Volunteering  : Which, if any, type(s) of volunteering have you done in the past 12 months?",
#                     "Was the formal volunteering that you did in the past 12 months your first time formally volunteering in Alberta? [Do formal volunteering]",
#                     "In the past 12 months, on average, about how many hours per month did you spend formally volunteering? [Do formal volunteering]",
#                     "[Bucketed] In the past 12 months, on average, about how many hours per month did you spend formally volunteering? [Do formal volunteering]",
#                     "Social Services : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
#                     "Faith-based Groups : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
#                     "Fundraising/Philanthropic Organizations : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
#                     "Sports & Recreation : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
#                     "Education & Research : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
#                     "Youth Development : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
#                     "Community Development : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
#                     "Environment : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
#                     "Unions & Professional Associations : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
#                     "Arts & Culture : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
#                     "Hospitals or Health : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
#                     "Law, Advocacy, & Politics : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
#                     "Other volunteer area : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
#                     "Other volunteer area : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]",
#                     "Micro Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]",
#                     "Virtual/ Online Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]",
#                     "Group Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]",
#                     "Employer Supported Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]",
#                     "None of the above : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]",
#                     "Friends, family members, or neighbours : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
#                     "Colleagues : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
#                     "Social Media : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
#                     "Employers : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
#                     "Volunteer Centers : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
#                     "Church / Religious group : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
#                     "Alberta Cares Connector, or the Volunteer Connector : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
#                     "Online / General web search  : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
#                     "Past experience : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
#                     "School / College / University : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
#                     "Sports teams / Sports organizations : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
#                     "Other : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]",
#                     "Other : How did you find out about the formal volunteering opportunities you participated in?",
#                     "In the past 12 months, on average, about how many hours per month did you spend informally volunteering? [Do informal volunteering]",
#                     "[Bucketed] In the past 12 months, on average, about how many hours per month did you spend informally volunteering? [Do informal volunteering]",
#                     "Was the informal volunteering you did in the past 12 months your first time informally volunteering in Alberta? [Do informal volunteering]"]

 Which, if any, type(s) of volunteering have you done in the past 12 months?
 Which, if any, type(s) of volunteering have you done in the past 12 months?
 Which, if any, type(s) of volunteering have you done in the past 12 months?
 Which, if any, type(s) of volunteering have you done in the past 12 months?
 Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]
 Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]
 Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]
 Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]
 Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]
 Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]
 Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]
 Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]
 Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]
 Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]
 Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]
 Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]
 Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]

ValueError: cannot reindex on an axis with duplicate labels

In [9]:
cleanData.head()

,What age range do you fall into?,What is the highest level of education you have completed?,What is your employment status?,"Do you have any children, living at home or that you are a legal guardian for, who are under 18 years old?","Formal volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?","Informal volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?","No volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?","Any Volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?",Was the formal volunteering that you did in the past 12 months your first time formally volunteering in Alberta? [Do formal volunteering],"In the past 12 months, on average, about how many hours per month did you spend formally volunteering? [Do formal volunteering]",...,Organizations that support group or family volunteering opportunities. : To what extent would each of the following make formal volunteering more appealing for you?,Organizations that are welcoming and inclusive to all Albertans. : To what extent would each of the following make formal volunteering more appealing for you?,Organizations that understand and work to meet the needs of my community. : To what extent would each of the following make formal volunteering more appealing for you?,Organizations that regularly recognize the contributions of volunteers. : To what extent would each of the following make formal volunteering more appealing for you?,Volunteers are important contributors to Alberta's economy. : To what extent do you agree with the following statements?,Volunteering is for people of all ages. : To what extent do you agree with the following statements?,"Whether large or small, all contributions by volunteers make a positive difference in the community. : To what extent do you agree with the following statements?",Provides an opportunity to give back to the community/make the community a better place to live. : To what extent do you agree that each of the following are benefits of volunteering?,Provides an opportunity to make meaningful connections with people. : To what extent do you agree that each of the following are benefits of volunteering?,Supports your own physical and/or mental health and wellness. : To what extent do you agree that each of the following are benefits of volunteering?
0,18 to 24,Graduated university,Student,No,Not selected,Not selected,Selected,Not selected,Skipped,Skipped,...,Moderately more appealing,Not at all,A lot more appealing,A little bit more appealing,Agree a little bit,Strongly agree,Moderately agree,Strongly agree,Moderately agree,Strongly agree
1,25 to 34,Graduated university,Working full-time,No,Not selected,Not selected,Selected,Not selected,Skipped,Skipped,...,Moderately more appealing,A little bit more appealing,Moderately more appealing,Moderately more appealing,Agree a little bit,Moderately agree,Strongly agree,Moderately agree,Agree a little bit,Moderately agree
2,18 to 24,"Graduated college, apprenticeship or trades",Working full-time,No,Refused,Refused,Refused,Refused,Skipped,Skipped,...,Don't know,Don't know,Don't know,Don't know,Don't know,Don't know,Don't know,Don't know,Don't know,Don't know
3,18 to 24,Not graduated from high school,Unemployed,No,Not selected,Selected,Not selected,Selected,Skipped,Skipped,...,Moderately more appealing,A lot more appealing,Moderately more appealing,A lot more appealing,Strongly agree,Strongly agree,Strongly agree,Moderately agree,Strongly agree,Moderately agree
4,18 to 24,Some university,Working part-time,No,Selected,Not selected,Not selected,Selected,No,Don't know,...,A lot more appealing,A lot more appealing,A lot more appealing,A lot more appealing,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Moderately agree

In [25]:
list(cleanData)

['What age range do you fall into?',
 'What is the highest level of education you have completed?',
 'What is your employment status?',
 'Do you have any children, living at home or that you are a legal guardian for, who are under 18 years old?',
 'Formal volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?',
 'Informal volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?',
 'No volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?',
 'Any Volunteering  : Which, if any, type(s) of volunteering have you done in the past 12 months?',
 'Was the formal volunteering that you did in the past 12 months your first time formally volunteering in Alberta? [Do formal volunteering]',
 'In the past 12 months, on average, about how many hours per month did you spend formally volunteering? [Do formal volunteering]',
 '[Bucketed] In the past 12 months, on average, about how many hours per month did you spend formally volunteering? [Do formal volunteering]',
 'Social Services : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Faith-based Groups : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Fundraising/Philanthropic Organizations : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Sports & Recreation : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Education & Research : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Youth Development : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Community Development : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Environment : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Unions & Professional Associations : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Arts & Culture : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Hospitals or Health : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Law, Advocacy, & Politics : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Other volunteer area : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Other volunteer area : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Other volunteer area : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Other volunteer area : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Micro Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]',
 'Virtual/ Online Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]',
 'Group Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]',
 'Employer Supported Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]',
 'None of the above : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]',
 'Friends, family members, or neighbours : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Colleagues : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Social Media : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Employers : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Volunteer Centers : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Church / Religious group : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Alberta Cares Connector, or the Volunteer Connector : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Online / General web search  : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Past experience : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'School / College / University : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Sports teams / Sports organizations : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Other : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Other : How did you find out about the formal volunteering opportunities you participated in?',
 'In the past 12 months, on average, about how many hours per month did you spend informally volunteering? [Do informal volunteering]',
 '[Bucketed] In the past 12 months, on average, about how many hours per month did you spend informally volunteering? [Do informal volunteering]',
 'Was the informal volunteering you did in the past 12 months your first time informally volunteering in Alberta? [Do informal volunteering]',
 'Opportunities did not match or improve my skill set : Which, if any, challenges have you ever been faced with when volunteering?',
 'Lack of available time : Which, if any, challenges have you ever been faced with when volunteering?',
 'Language Skills : Which, if any, challenges have you ever been faced with when volunteering?',
 'Personal Health : Which, if any, challenges have you ever been faced with when volunteering?',
 'Age : Which, if any, challenges have you ever been faced with when volunteering?',
 'Cost/Financial : Which, if any, challenges have you ever been faced with when volunteering?',
 'Location of volunteering : Which, if any, challenges have you ever been faced with when volunteering?',
 'Finding Volunteer opportunities : Which, if any, challenges have you ever been faced with when volunteering?',
 'No one asked : Which, if any, challenges have you ever been faced with when volunteering?',
 'Unhappy with previous volunteer experience(s) : Which, if any, challenges have you ever been faced with when volunteering?',
 'Lack of flexible scheduling : Which, if any, challenges have you ever been faced with when volunteering?',
 'Lack of support for volunteering at different locations : Which, if any, challenges have you ever been faced with when volunteering?',
 'Did not accommodate groups or families : Which, if any, challenges have you ever been faced with when volunteering?',
 'Did not offer accommodations to those with health issues : Which, if any, challenges have you ever been faced with when volunteering?',
 'Did not appear to be welcoming and inclusive to all Albertans : Which, if any, challenges have you ever been faced with when volunteering?',
 'Unclear or unreasonable expectations : Which, if any, challenges have you ever been faced with when volunteering?',
 'Volunteer recruitment or interview processes : Which, if any, challenges have you ever been faced with when volunteering?',
 'Required too much or too little of my time : Which, if any, challenges have you ever been faced with when volunteering?',
 'Other challenges : Which, if any, challenges have you ever been faced with when volunteering?',
 'Other challenges : Which, if any, challenges have you ever been faced with when volunteering?',
 'None of the above : Which, if any, challenges have you ever been faced with when volunteering?',
 'I have never volunteered : Which, if any, challenges have you ever been faced with when volunteering?',
 'Other challenges : Which, if any, challenges have you ever been faced with when volunteering?',
 'Other challenges : Which, if any, challenges have you ever been faced with when volunteering?',
 'Access to volunteer opportunities that match and help improve my skill set. : To what extent would each of the following make formal volunteering more appealing for you?',
 'Access to volunteer opportunities that offer flexible schedules. : To what extent would each of the following make formal volunteering more appealing for you?',
 'Access to volunteer opportunities that offer training with current technology : To what extent would each of the following make formal volunteering more appealing for you?',
 'Organizations that support different ways of volunteering : To what extent would each of the following make formal volunteering more appealing for you?',
 'Organizations that support group or family volunteering opportunities. : To what extent would each of the following make formal volunteering more appealing for you?',
 'Organizations that are welcoming and inclusive to all Albertans. : To what extent would each of the following make formal volunteering more appealing for you?',
 'Organizations that understand and work to meet the needs of my community. : To what extent would each of the following make formal volunteering more appealing for you?',
 'Organizations that regularly recognize the contributions of volunteers. : To what extent would each of the following make formal volunteering more appealing for you?',
 "Volunteers are important contributors to Alberta's economy. : To what extent do you agree with the following statements?",
 'Volunteering is for people of all ages. : To what extent do you agree with the following statements?',
 'Whether large or small, all contributions by volunteers make a positive difference in the community. : To what extent do you agree with the following statements?',
 'Provides an opportunity to give back to the community/make the community a better place to live. : To what extent do you agree that each of the following are benefits of volunteering?',
 'Provides an opportunity to make meaningful connections with people. : To what extent do you agree that each of the following are benefits of volunteering?',
 'Supports your own physical and/or mental health and wellness. : To what extent do you agree that each of the following are benefits of volunteering?',
 'Combined_Which,_if_any,_type(s)_of_volunteering_have_you_done_in_the_past_12_months']

In [11]:
fullData = cleanData.copy()

# Group questions by what's after the colon
volunteering_groups = {}

# First, group columns by their question text
for col in volunteeringBehaviour:
    if ':' in col:
        option = col.split(':', 1)[0].strip()
        question_text = col.split(':', 1)[1].strip()
        
        # Remove any conditional text in square brackets for the question name
        if '[' in question_text:
            question_text = question_text.split('[', 1)[0].strip()
            
        if question_text not in volunteering_groups:
            volunteering_groups[question_text] = []
        
        volunteering_groups[question_text].append((col, option))
    else:
        # Questions without colons get copied directly
        new_df[col] = renamedOnline22[col]

# Now process each question group
for question, columns in volunteering_groups.items():
    # For binary columns (Selected/Not selected pattern)
    if "Which, if any, type(s) of volunteering" in question:
        selected_options = []
        
        for idx in renamedOnline22.index:
            row_options = []
            for col, option in columns:
                # Check if this option was selected
                if pd.notna(renamedOnline22.loc[idx, col]) and "Selected" in str(renamedOnline22.loc[idx, col]):
                    row_options.append(option)
            
            selected_options.append(', '.join(row_options) if row_options else np.nan)
        
        new_df[question] = selected_options
    
    # For "Which areas did you formally volunteer in" question
    elif "Which areas did you formally volunteer in" in question:
        selected_areas = []
        
        for idx in renamedOnline22.index:
            areas = []
            for col, option in columns:
                if pd.notna(renamedOnline22.loc[idx, col]) and "Selected" in str(renamedOnline22.loc[idx, col]):
                    areas.append(option)
            
            selected_areas.append(', '.join(areas) if areas else np.nan)
        
        new_df[question] = selected_areas
    
    # For "Was any of the formal volunteer work" question
    elif "Was any of the formal volunteer work" in question:
        selected_types = []
        
        for idx in renamedOnline22.index:
            types = []
            for col, option in columns:
                if pd.notna(renamedOnline22.loc[idx, col]) and "Selected" in str(renamedOnline22.loc[idx, col]):
                    types.append(option)
            
            selected_types.append(', '.join(types) if types else np.nan)
        
        new_df[question] = selected_types
    
    # For "How did you find out about" question
    elif "How did you find out about" in question:
        selected_sources = []
        
        for idx in renamedOnline22.index:
            sources = []
            for col, option in columns:
                if pd.notna(renamedOnline22.loc[idx, col]) and "Selected" in str(renamedOnline22.loc[idx, col]):
                    sources.append(option)
            
            selected_sources.append(', '.join(sources) if sources else np.nan)
        
        new_df[question] = selected_sources

NameError: name 'new_df' is not defined

In [13]:
list(cleanData.columns.values)

['What age range do you fall into?',
 'What is the highest level of education you have completed?',
 'What is your employment status?',
 'Do you have any children, living at home or that you are a legal guardian for, who are under 18 years old?',
 'Formal volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?',
 'Informal volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?',
 'No volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?',
 'Any Volunteering  : Which, if any, type(s) of volunteering have you done in the past 12 months?',
 'Was the formal volunteering that you did in the past 12 months your first time formally volunteering in Alberta? [Do formal volunteering]',
 'In the past 12 months, on average, about how many hours per month did you spend formally volunteering? [Do formal volunteering]',
 '[Bucketed] In the past 12 months, on average, about how many hours per month did you spend formally volunteering? [Do formal volunteering]',
 'Social Services : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Faith-based Groups : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Fundraising/Philanthropic Organizations : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Sports & Recreation : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Education & Research : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Youth Development : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Community Development : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Environment : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Unions & Professional Associations : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Arts & Culture : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Hospitals or Health : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Law, Advocacy, & Politics : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Other volunteer area : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Other volunteer area : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Other volunteer area : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Other volunteer area : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Micro Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]',
 'Virtual/ Online Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]',
 'Group Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]',
 'Employer Supported Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]',
 'None of the above : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]',
 'Friends, family members, or neighbours : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Colleagues : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Social Media : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Employers : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Volunteer Centers : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Church / Religious group : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Alberta Cares Connector, or the Volunteer Connector : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Online / General web search  : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Past experience : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'School / College / University : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Sports teams / Sports organizations : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Other : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Other : How did you find out about the formal volunteering opportunities you participated in?',
 'In the past 12 months, on average, about how many hours per month did you spend informally volunteering? [Do informal volunteering]',
 '[Bucketed] In the past 12 months, on average, about how many hours per month did you spend informally volunteering? [Do informal volunteering]',
 'Was the informal volunteering you did in the past 12 months your first time informally volunteering in Alberta? [Do informal volunteering]',
 'Opportunities did not match or improve my skill set : Which, if any, challenges have you ever been faced with when volunteering?',
 'Lack of available time : Which, if any, challenges have you ever been faced with when volunteering?',
 'Language Skills : Which, if any, challenges have you ever been faced with when volunteering?',
 'Personal Health : Which, if any, challenges have you ever been faced with when volunteering?',
 'Age : Which, if any, challenges have you ever been faced with when volunteering?',
 'Cost/Financial : Which, if any, challenges have you ever been faced with when volunteering?',
 'Location of volunteering : Which, if any, challenges have you ever been faced with when volunteering?',
 'Finding Volunteer opportunities : Which, if any, challenges have you ever been faced with when volunteering?',
 'No one asked : Which, if any, challenges have you ever been faced with when volunteering?',
 'Unhappy with previous volunteer experience(s) : Which, if any, challenges have you ever been faced with when volunteering?',
 'Lack of flexible scheduling : Which, if any, challenges have you ever been faced with when volunteering?',
 'Lack of support for volunteering at different locations : Which, if any, challenges have you ever been faced with when volunteering?',
 'Did not accommodate groups or families : Which, if any, challenges have you ever been faced with when volunteering?',
 'Did not offer accommodations to those with health issues : Which, if any, challenges have you ever been faced with when volunteering?',
 'Did not appear to be welcoming and inclusive to all Albertans : Which, if any, challenges have you ever been faced with when volunteering?',
 'Unclear or unreasonable expectations : Which, if any, challenges have you ever been faced with when volunteering?',
 'Volunteer recruitment or interview processes : Which, if any, challenges have you ever been faced with when volunteering?',
 'Required too much or too little of my time : Which, if any, challenges have you ever been faced with when volunteering?',
 'Other challenges : Which, if any, challenges have you ever been faced with when volunteering?',
 'Other challenges : Which, if any, challenges have you ever been faced with when volunteering?',
 'None of the above : Which, if any, challenges have you ever been faced with when volunteering?',
 'I have never volunteered : Which, if any, challenges have you ever been faced with when volunteering?',
 'Other challenges : Which, if any, challenges have you ever been faced with when volunteering?',
 'Other challenges : Which, if any, challenges have you ever been faced with when volunteering?',
 'Access to volunteer opportunities that match and help improve my skill set. : To what extent would each of the following make formal volunteering more appealing for you?',
 'Access to volunteer opportunities that offer flexible schedules. : To what extent would each of the following make formal volunteering more appealing for you?',
 'Access to volunteer opportunities that offer training with current technology : To what extent would each of the following make formal volunteering more appealing for you?',
 'Organizations that support different ways of volunteering : To what extent would each of the following make formal volunteering more appealing for you?',
 'Organizations that support group or family volunteering opportunities. : To what extent would each of the following make formal volunteering more appealing for you?',
 'Organizations that are welcoming and inclusive to all Albertans. : To what extent would each of the following make formal volunteering more appealing for you?',
 'Organizations that understand and work to meet the needs of my community. : To what extent would each of the following make formal volunteering more appealing for you?',
 'Organizations that regularly recognize the contributions of volunteers. : To what extent would each of the following make formal volunteering more appealing for you?',
 "Volunteers are important contributors to Alberta's economy. : To what extent do you agree with the following statements?",
 'Volunteering is for people of all ages. : To what extent do you agree with the following statements?',
 'Whether large or small, all contributions by volunteers make a positive difference in the community. : To what extent do you agree with the following statements?',
 'Provides an opportunity to give back to the community/make the community a better place to live. : To what extent do you agree that each of the following are benefits of volunteering?',
 'Provides an opportunity to make meaningful connections with people. : To what extent do you agree that each of the following are benefits of volunteering?',
 'Supports your own physical and/or mental health and wellness. : To what extent do you agree that each of the following are benefits of volunteering?']

In [14]:
mixedColList = ['Formal volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?',
 'Informal volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?',
 'No volunteering : Which, if any, type(s) of volunteering have you done in the past 12 months?',
 'Any Volunteering  : Which, if any, type(s) of volunteering have you done in the past 12 months?',
 'Was the formal volunteering that you did in the past 12 months your first time formally volunteering in Alberta? [Do formal volunteering]',
 'In the past 12 months, on average, about how many hours per month did you spend formally volunteering? [Do formal volunteering]',
 '[Bucketed] In the past 12 months, on average, about how many hours per month did you spend formally volunteering? [Do formal volunteering]',
 'Social Services : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Faith-based Groups : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Fundraising/Philanthropic Organizations : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Sports & Recreation : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Education & Research : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Youth Development : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Community Development : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Environment : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Unions & Professional Associations : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Arts & Culture : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Hospitals or Health : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Law, Advocacy, & Politics : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Other volunteer area : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Other volunteer area : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Other volunteer area : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Other volunteer area : Which areas did you formally volunteer in over the past 12 months? [Do formal volunteering]',
 'Micro Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]',
 'Virtual/ Online Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]',
 'Group Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]',
 'Employer Supported Volunteering : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]',
 'None of the above : Was any of the formal volunteer work you did in the past 12 months ...? [Do formal volunteering]',
 'Friends, family members, or neighbours : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Colleagues : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Social Media : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Employers : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Volunteer Centers : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Church / Religious group : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Alberta Cares Connector, or the Volunteer Connector : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Online / General web search  : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Past experience : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'School / College / University : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Sports teams / Sports organizations : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Other : How did you find out about the formal volunteering opportunities you participated in? [Do formal volunteering]',
 'Other : How did you find out about the formal volunteering opportunities you participated in?',
 'In the past 12 months, on average, about how many hours per month did you spend informally volunteering? [Do informal volunteering]',
 '[Bucketed] In the past 12 months, on average, about how many hours per month did you spend informally volunteering? [Do informal volunteering]',
 'Was the informal volunteering you did in the past 12 months your first time informally volunteering in Alberta? [Do informal volunteering]',
 'Opportunities did not match or improve my skill set : Which, if any, challenges have you ever been faced with when volunteering?',
 'Lack of available time : Which, if any, challenges have you ever been faced with when volunteering?',
 'Language Skills : Which, if any, challenges have you ever been faced with when volunteering?',
 'Personal Health : Which, if any, challenges have you ever been faced with when volunteering?',
 'Age : Which, if any, challenges have you ever been faced with when volunteering?',
 'Cost/Financial : Which, if any, challenges have you ever been faced with when volunteering?',
 'Location of volunteering : Which, if any, challenges have you ever been faced with when volunteering?',
 'Finding Volunteer opportunities : Which, if any, challenges have you ever been faced with when volunteering?',
 'No one asked : Which, if any, challenges have you ever been faced with when volunteering?',
 'Unhappy with previous volunteer experience(s) : Which, if any, challenges have you ever been faced with when volunteering?',
 'Lack of flexible scheduling : Which, if any, challenges have you ever been faced with when volunteering?',
 'Lack of support for volunteering at different locations : Which, if any, challenges have you ever been faced with when volunteering?',
 'Did not accommodate groups or families : Which, if any, challenges have you ever been faced with when volunteering?',
 'Did not offer accommodations to those with health issues : Which, if any, challenges have you ever been faced with when volunteering?',
 'Did not appear to be welcoming and inclusive to all Albertans : Which, if any, challenges have you ever been faced with when volunteering?',
 'Unclear or unreasonable expectations : Which, if any, challenges have you ever been faced with when volunteering?',
 'Volunteer recruitment or interview processes : Which, if any, challenges have you ever been faced with when volunteering?',
 'Required too much or too little of my time : Which, if any, challenges have you ever been faced with when volunteering?',
 'Other challenges : Which, if any, challenges have you ever been faced with when volunteering?',
 'Other challenges : Which, if any, challenges have you ever been faced with when volunteering?',
 'None of the above : Which, if any, challenges have you ever been faced with when volunteering?',
 'I have never volunteered : Which, if any, challenges have you ever been faced with when volunteering?',
 'Other challenges : Which, if any, challenges have you ever been faced with when volunteering?',
 'Other challenges : Which, if any, challenges have you ever been faced with when volunteering?',
 'Access to volunteer opportunities that match and help improve my skill set. : To what extent would each of the following make formal volunteering more appealing for you?',
 'Access to volunteer opportunities that offer flexible schedules. : To what extent would each of the following make formal volunteering more appealing for you?',
 'Access to volunteer opportunities that offer training with current technology : To what extent would each of the following make formal volunteering more appealing for you?',
 'Organizations that support different ways of volunteering : To what extent would each of the following make formal volunteering more appealing for you?',
 'Organizations that support group or family volunteering opportunities. : To what extent would each of the following make formal volunteering more appealing for you?',
 'Organizations that are welcoming and inclusive to all Albertans. : To what extent would each of the following make formal volunteering more appealing for you?',
 'Organizations that understand and work to meet the needs of my community. : To what extent would each of the following make formal volunteering more appealing for you?',
 'Organizations that regularly recognize the contributions of volunteers. : To what extent would each of the following make formal volunteering more appealing for you?',
 "Volunteers are important contributors to Alberta's economy. : To what extent do you agree with the following statements?",
 'Volunteering is for people of all ages. : To what extent do you agree with the following statements?',
 'Whether large or small, all contributions by volunteers make a positive difference in the community. : To what extent do you agree with the following statements?',
 'Provides an opportunity to give back to the community/make the community a better place to live. : To what extent do you agree that each of the following are benefits of volunteering?',
 'Provides an opportunity to make meaningful connections with people. : To what extent do you agree that each of the following are benefits of volunteering?',
 'Supports your own physical and/or mental health and wellness. : To what extent do you agree that each of the following are benefits of volunteering?']

# First group columns by their question text
question_groups = {}

In [16]:
volunteeringData = cleanData[]

SyntaxError: invalid syntax (2351385136.py, line 1)

# Exploratory Analysis

In [17]:
#Age
cleanData["What age range do you fall into?"].value_counts()

What age range do you fall into?
25 to 34       336
55 to 64       325
65 or older    321
35 to 44       268
45 to 54       247
18 to 24        67
Name: count, dtype: int64

In [18]:
#Who has volunteered?
cleanData["Any Volunteering  : Which, if any, type(s) of volunteering have you done in the past 12 months?"].value_counts()

Any Volunteering  : Which, if any, type(s) of volunteering have you done in the past 12 months?
Selected        970
Not selected    561
 Refused         21
 Don't know      12
Name: count, dtype: int64

In [19]:
# Employment Status
cleanData["What is your employment status?"].value_counts()

What is your employment status?
Working full-time        750
Retired                  333
Self-employed            159
Working part-time        135
Unemployed                88
Student                   37
Other                     36
 Prefer not to answer     26
Name: count, dtype: int64

In [20]:
#Employment status of older individuals
condition = (cleanData["What age range do you fall into?"] == "65 or older") | (cleanData["What age range do you fall into?"] == "55 to 64")
cleanData[condition]["What is your employment status?"].value_counts()

What is your employment status?
Retired                  327
Working full-time        169
Self-employed             71
Working part-time         44
Unemployed                15
Other                     11
 Prefer not to answer      8
Student                    1
Name: count, dtype: int64

# Exploratory Plots

In [21]:
demographics = cleanData[demographicQuestions]
demographics = demographics.dropna()
demographics.head()

,What age range do you fall into?,What is the highest level of education you have completed?,What is your employment status?,"Do you have any children, living at home or that you are a legal guardian for, who are under 18 years old?"
0,18 to 24,Graduated university,Student,No
1,25 to 34,Graduated university,Working full-time,No
2,18 to 24,"Graduated college, apprenticeship or trades",Working full-time,No
3,18 to 24,Not graduated from high school,Unemployed,No
4,18 to 24,Some university,Working part-time,No

In [22]:
fig = px.histogram(
    demographics, 
    x="What is the highest level of education you have completed?",
    color="What is your employment status?",
    title='Education Level Distribution by Employment Status',
    labels={
        education_col: 'Education Level',
        'count': 'Number of Respondents'
    },
    height=500
)

# Improve readability
fig.update_layout(
    xaxis={'categoryorder':'total descending'},
    legend_title="Employment Status"
)

fig.show()

NameError: name 'education_col' is not defined

In [23]:

fig = px.histogram(
    demographics, 
    x="What is the highest level of education you have completed?",
    color="What is your employment status?",
    title='Education Level Distribution by Employment Status',
    labels={
        education_col: 'Education Level',
        'count': 'Number of Respondents'
    },
    height=500
)

# Improve readability
fig.update_layout(
    xaxis={'categoryorder':'total descending'},
    legend_title="Employment Status"
)

fig.show()

NameError: name 'education_col' is not defined